# Generated by Django 4.2 on 2023-05-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregister',
            table=None,
        ),
    ]
